import About from '@/components/about'
import Main from '@/components/main'
import Projects from '@/components/projects'
import Skills from '@/components/skills'
import Head from 'next/head'
import Contacts from '@/components/contacts'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portofolio | Ikhwanul Abiyu D H</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Main/>
    <About/>
    <Skills/>
    <Projects/>
    <Contacts/>
    </div>
  )
}
